version: '3'

services:
  devweek_webapp:
    image: devweek_webapp
    build:
      context: .
      dockerfile: DevWeek.WebApp/Dockerfile
    networks:
      - devweek-net

  devweek_worker:
    image: devweek_worker
    build:
      context: .
      dockerfile: DevWeek.Worker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_data:/shared
    networks:
      - devweek-net
    depends_on:
      - s3
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    networks:
      - devweek-net
    environment:
      RABBITMQ_DEFAULT_USER: devweek
      RABBITMQ_DEFAULT_PASS: UCpkGkG37xgDzNvG6rbkGDuVeyNc4vlcVtDorn3wPFhR9URvhDN6cSeOzL4HXN3u4Z3Ahv
      RABBITMQ_DEFAULT_VHOST: platform

  s3:
    image: minio/minio
    volumes:
      - s3_data:/data
      - s3_config:/root/.minio
    command: server /data
    networks:
      - devweek-net
    ports:
      - "7000:9000"
    environment:
      MINIO_ACCESS_KEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRET_KEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy

  redis:
    image: redis:alpine
    networks:
      - devweek-net

volumes:  
  mq_data:
  s3_data:
  s3_config:
  shared_data:

networks: 
  devweek-net: 
    driver: bridge