networks:
  devweek_net: {}
services:
  devweek_webapp:
    depends_on:
    - mongodb
    - rabbitmq
    - redis
    - s3
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    image: 'luizcarlosfaria/devweek_webapp:'
    networks:
      devweek_net: null
    restart: unless-stopped
  devweek_worker:
    build:
      context: C:\_dev\_OSS\devweek2017--ci-cd-jenkins-netcore\src
      dockerfile: DevWeek.Worker/Dockerfile
    depends_on:
    - mongodb
    - rabbitmq
    - redis
    - s3
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 600s
      update_config:
        delay: 10s
        order: start-first
        parallelism: 1
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    image: 'luizcarlosfaria/devweek_worker:'
    networks:
      devweek_net: null
    restart: unless-stopped
    volumes:
    - shared_data:/shared:rw
    - \var\run\docker.sock:/var/run/docker.sock:rw
  mongodb:
    command: --storageEngine wiredTiger
    environment:
      MONGO_INITDB_ROOT_PASSWORD: eprPs2UEJ239RvH7SicPkcFbkTQoa8
      MONGO_INITDB_ROOT_USERNAME: mongouser
    image: mongo:3.4
    networks:
      devweek_net: null
    ports:
    - published: 20205
      target: 27017
    restart: always
    volumes:
    - mongo_data:/data/db:rw
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: UCpkGkG37xgDzNvG6rbkGDuVeyNc4vlcVtDorn3wPFhR9URvhDN6cSeOzL4HXN3u4Z3Ahv
      RABBITMQ_DEFAULT_USER: devweek
      RABBITMQ_DEFAULT_VHOST: platform
    image: rabbitmq:3-management-alpine
    networks:
      devweek_net: null
    ports:
    - published: 20202
      target: 15672
    volumes:
    - mq_data:/var/lib/rabbitmq/mnesia:rw
  redis:
    image: redis:alpine
    networks:
      devweek_net: null
    ports:
    - published: 20204
      target: 6379
  s3:
    command: server /data
    environment:
      MINIO_ACCESS_KEY: Zu8VgBoZMU2xcmOEeS70
      MINIO_SECRET_KEY: xvnjYyFQyFs44iuUagi4kTHiOGvlK1PiX64LiwOy
    image: minio/minio
    networks:
      devweek_net: null
    ports:
    - published: 20203
      target: 9000
    volumes:
    - s3_data:/data:rw
    - s3_config:/root/.minio:rw
version: '3.4'
volumes:
  mongo_data: {}
  mq_data: {}
  s3_config: {}
  s3_data: {}
  shared_data: {}

