version: '3'

services:
  devweek_webapp:
    image: devweek_webapp:dev-latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - "20001:80"

  devweek_worker:
    image: devweek_worker:dev-latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    ports: 
      - "20002:15672"

  s3:
    ports: 
      - "20003:15672"

  redis:
    ports:
      - "20004:6379"
