version: '3.4'

services:
  devweek_webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
#    deploy:
#      placement:
#        constraints: 
#          - node.labels.appenv == prd
      

  
  
  
  
  
  devweek_worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 600s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
#      placement:
#        constraints: 
#          - node.labels.appenv == prd


  rabbitmq:
    ports: 
      - "20202:15672"
#    deploy:
#      placement:
#        constraints: 
#          - node.labels.appenv == prd

  s3:
    ports: 
      - "20203:9000"
#    deploy:
#      placement:
#        constraints: 
#          - node.labels.appenv == prd

  redis:
    ports:
      - "20204:6379"
#    deploy:
#      placement:
#        constraints: 
#          - node.labels.appenv == prd

  mongodb:
    ports:
      - "20205:27017"
#    deploy:
#      placement:
#        constraints: 
#          - node.labels.appenv == prd