version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet sln ./src.sln remove docker-compose.dcproj &&  dotnet restore ./src.sln && dotnet test ./DevWeek.Services.Tests/DevWeek.Services.Tests.csproj --logger \"trx;LogFileName=unit_tests.xml\" && dotnet publish ./src.sln -c Release -o ./obj/Docker/publish"
